@startuml dmx_interface
    state "send frame" as send_frame {
        state "send break" as sf_break
        state "send MAB" as sf_MAB
        state "send start code" as sf_start
        state "send payload" as sf_payload {
            
        }
        
        [*] -d-> sf_break
        sf_break -d-> sf_MAB
        sf_MAB -d-> sf_start
        sf_start -d-> sf_payload
        sf_payload -d-> [*]
    }
    state "idle" as sys_idle
    state "init" as sys_init

    [*] -> sys_init
    sys_init -> sys_idle
    sys_idle -> send_frame : call with 44Hz
    send_frame -> sys_idle
@enduml